### ISSUE TITLE
term_extractor reference

### ISSUE THREAD

**Issue by pvcastro** [kevinlu1248/pyate#10]
Hi there!

Where did you get the specs for the `term_extractor` component? Is it only from _TermExtractor: a Web Application to Learn the Shared Terminology of Emergent Web Communities_? If there's anything else, can you please indicate the reference?
It's not related in the benchmark from _Astrakhantsev 2016_, is it? Which one would be the closest approach to it?

Thanks, and great work!

**Comment by kevinlu1248** [comment]
Hi there, thanks for asking for clarification. Yes, `term_extractor` is purely based on _TermExtractor: a Web Application to Learn the Shared Terminology of Emergent Web Communities_, which is implemented identically to _Astrakhantsev 2016_, who, like _Sclano and Velardi 2007_ and myself, also used the 1/3,1/3,1/3 split between the weights for domain pertinence, domain consensus and lexical cohesion.

If you would like clarification on what domain pertinence, domain consensus and lexical cohesion are you can check out the paper or I can define here.

**Comment by pvcastro** [comment]
If you don't mind, can you please clarify? The TermExtractor paper is really short, I only grasped from it that these are manually evaluated by domain specialists, but I couldn't get their concept. 

What caught my attention is that it also uses a general corpus as reference, and this seems very appropriate to me.

In the end, the best candidates are the ones that have the highest weighed scores for each of them, right?

Thanks for the response!

**Comment by kevinlu1248** [comment]
The Springer link I sited under the README.md shows only the introductory pages but I found a free copy elsewhere, attached  here [a8e57bb30763f8abb1de2f7c26a4afefb304.pdf](https://github.com/kevinlu1248/pyate/files/5005417/a8e57bb30763f8abb1de2f7c26a4afefb304.pdf). The following latex are rendered by https://www.codecogs.com/latex/eqneditor.php. 

Feel free to ask for clarification if any of the following does not make sense. @pvcastro 

## TermExtractor
In summary, the algorithm provides for each term candidate a weighted mean of three scores which can be interpreted as probabilities as the "termhood", that is, the probability of the candidate phrase being a term, after filtering the term candidates from a domain sequences of words following some POS pattern (such as adjective/noun). As a clarification, "term candidate" or just "candidate" denotes a string of words that may be a term that we do not know of yet. We have the following definitions.

### Domain Pertinence (DR)
Let Di be the domain of interest among D1, D2, ... Dn, then

![image](https://user-images.githubusercontent.com/26889185/89005877-5b8def80-d2ba-11ea-99e8-a7928be89ff0.png)

where ![image](https://user-images.githubusercontent.com/26889185/89006052-b6274b80-d2ba-11ea-94e6-451803b526ce.png) is simply the frequency of the term candidate t in domain D. In our case specifically, since we only have two domains (general and technical) PR is equivalent to 1 if the term candidate occurs more frequently in the technical domain than the general domain, otherwise use 
![image](https://user-images.githubusercontent.com/26889185/89006339-6301c880-d2bb-11ea-811f-03998534ff2e.png), where D_T and D_G are the technical and general domain respectively.

### Domain Consensus (DC)
The domain consensus is the Shannon entropy of the term candidate, which is high when the term candidate occurs evenly throughout the domain. 

![image](https://user-images.githubusercontent.com/26889185/89006951-a14bb780-d2bc-11ea-9b50-b024872357f6.png)

Where norm_freq is the normalized frequency of the term candidate t in document d.

### Lexical Cohesion (LC)
The lexical cohesion increases as the term candidate itself appears more frequently and its parts appear less frequently.

![image](https://user-images.githubusercontent.com/26889185/89007189-26cf6780-d2bd-11ea-84e6-23843f8b5b8c.png)

where |t| is the length of the term candidate (number of words) and w makes the set of words composing the candidate t. For example, if the term candidate is "natural language processing", then the denominator would sum over "natural", "language" and "processing". Furthermore, in the case that the words that compose the candidate appears only in the document within the term candidate itself, then the lexical cohesion simplifies to its upper bound
![image](https://user-images.githubusercontent.com/26889185/89007555-d278b780-d2bd-11ea-841b-e337f219df0a.png), and the upper bound is approached by minimizing the number of times the candidate's composing words occur outside the candidate itself.

### The Mean
TermExtractor and `pyate` by default will use the weights 1/3,1/3,1/3 for taking the mean of the three scores, yielding the final equation

![image](https://user-images.githubusercontent.com/26889185/89008172-0b655c00-d2bf-11ea-891c-df8eaf2e0489.png)

but you can vary this using the `weights` parameter.

**Comment by pvcastro** [comment]
Great, thanks @kevinlu1248 ! That was an excellent explanation.
I'll evaluate these algorithms in my technical corpus to see how each of them performs.
