### ISSUE TITLE
log in C-value

### ISSUE THREAD

**Issue by BinHeRunning** [kevinlu1248/pyate#15]
https://github.com/kevinlu1248/pyate/blob/4a61dbf42b85bf87c0f373da5b3af48747de8d23/src/pyate/cvalues.py#L71

From the original paper, log2 is used to calculate the C-value, but log is used in this code.

**Comment by kevinlu1248** [comment]
Thanks for the fix and the PR at https://github.com/kevinlu1248/pyate/pull/17. Using 0 as the threshold, it wouldn't make a difference since different log bases only change the result by a constant multiplier if my calculations are correct but staying true to the algorithm might fix issues in the future.
