### ISSUE TITLE
How did this ‘matcher‘ come into play later?Can you explain further?

### ISSUE THREAD

**Issue by ScottishFold007** [kevinlu1248/pyate#35]
How did this ‘matcher‘ come into play later?Can you explain further?
![image](https://user-images.githubusercontent.com/36957508/114518413-e9a3dd80-9c71-11eb-9204-cb9e0b65e893.png)

I tried to change to spacy 3.0 to analyze it, and nothing happened...
![image](https://user-images.githubusercontent.com/36957508/114518780-4b644780-9c72-11eb-8b1b-3d1df7f7882e.png)

**Comment by kevinlu1248** [comment]
I apologize for the delay due to the approach of exam season.

Firstly, spaCy v3.0 is currently not supported, I am looking to fix this soon since it should be a small fix. Secondly, can you indicate the version you are using as well as the string you are running with? It looks like your code made be out of date since line 205 says `new_matcher.add("term{}".format(i), add_to_counter, pattern)` but on your end it says something different. 

And to answer your question, it was named `new_matcher` due to realizing that this caused performance issues (https://github.com/kevinlu1248/pyate/issues/20).

**Comment by kevinlu1248** [comment]
@ScottishFold007 Does my answer above answer your question?

**Comment by ScottishFold007** [comment]
> @ScottishFold007 Does my answer above answer your question?

Yes,Thanks~
