### ISSUE TITLE
may be error in combo_basic.py

### ISSUE THREAD

**Issue by jamestch** [kevinlu1248/pyate#53]
hi, I have readed the source code in combo_basic.py, there is one palce that confused me. May U help?
in ART4S paper, combo_basic method formula is:
      ComboBasic(t)=|t|logf(t)+αet+βe′t
but the code in line 65 in combo_basic.py file is:
     lambda s: math.log(TermExtraction.word_length(s["index"])) * s[0]
I think it should be:
    lambda s: TermExtraction.word_length(s["index"]) * math.log(s[0])
since |t|=TermExtraction.word_length(s["index"]) and f(t)=s[0]
am I right, hope your help?

**Comment by bryan-johnston** [comment]
@jamestch Yes, you are correct. Kind of a horrible bug. I wasted a lot of time debugging my own code, since I wasn't getting expected results.
See [https://github.com/ziqizhang/jate/blob/master/src/main/java/uk/ac/shef/dcs/jate/algorithm/ComboBasicWorker.java](https://github.com/ziqizhang/jate/blob/master/src/main/java/uk/ac/shef/dcs/jate/algorithm/ComboBasicWorker.java)

**Comment by kevinlu1248** [comment]
Nice catch. Sorry for the bug.
